# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Hyphenate Messenger' do
    
    pod 'GoogleCloudMessaging', '~> 1.2'
    pod 'Google/Analytics'

    pod 'Fabric', '~> 1.6'

    pod 'Crashlytics'

    pod 'Parse'
    pod 'SlimeRefresh'

end


